server:
  port: 9090
spring:
  datasource:
    password: #DATABASE PASSWORD
    url: #DATABASE URL
    username: #DATABASE USERNAME
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: #GMAIL ID
    password: #GMAIL PASSWORD
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

          